jwcm/urls.py
from django.contrib import admin
from django.urls import path, include
from jwcm.core.views import About, CongregationUpdate, PersonList, PersonCreate, \
    PersonUpdate, PersonDelete, person_batch_create, home, \
    MechanicalPrivilegesListView, MechanicalPrivilegesUpdateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('public_speeches/', include('jwcm.public_speeches.urls')),
    path('life_and_ministry/', include('jwcm.life_and_ministry.urls')),
    path('users/', include('jwcm.users.urls')),
    path('lpw/', include('jwcm.lpw.urls')),
    path('reports/', include('jwcm.reports.urls')),

    path('', home, name='home'),
    path('about/', About.as_view(), name='about'),

    path('congregation/<int:pk>/', CongregationUpdate.as_view(), name='congregation'),

    path('person/', PersonList.as_view(), name='person-list'),
    path('person/create/', PersonCreate.as_view(), name='person-create'),
    path('person/update/<int:pk>/', PersonUpdate.as_view(), name='person-update'),
    path('person/delete/<int:pk>/', PersonDelete.as_view(), name='person-delete'),
    path('person/create/batch/', person_batch_create, name='person-batch-create'),

    path('mechanical_privileges/', MechanicalPrivilegesListView.as_view(), name='mechanical-privileges-list'),
    path('mechanical_privileges/<int:pk>/', MechanicalPrivilegesUpdateView.as_view(), name='mechanical-privileges-update'),


]

jwcm/core/models.py
from django.db.models import Q, UniqueConstraint
from django.db import models
from datetime import time
from django.urls import reverse_lazy
from jwcm.core.managers import PersonQuerySet, MeetingQuerySet, CongregationQuerySet
from jwcm.public_speeches.models import Speech


class Congregation(models.Model):
    SEGUNDA = 0
    TERCA = 1
    QUARTA = 2
    QUINTA = 3
    SEXTA = 4
    SABADO = 5
    DOMINGO = 6

    DAY_OF_WEEK = (
        (SEGUNDA, 'Segunda-feira'),
        (TERCA, 'Terça-feira'),
        (QUARTA, 'Quarta-feira'),
        (QUINTA, 'Quinta-feira'),
        (SEXTA, 'Sexta-feira'),
        (SABADO, 'Sábado'),
        (DOMINGO, 'Domingo'),
    )

    name = models.CharField(max_length=50, verbose_name='Nome')
    number = models.IntegerField(unique=True, verbose_name='Número', null=True)
    midweek_meeting_time = models.TimeField(verbose_name='Horário da reunião de meio de semana',
                                            default=time(19, 30, 00), null=True)
    weekend_meeting_time = models.TimeField(verbose_name='Horário da reunião de fim de semana',
                                            default=time(18, 00, 00), null=True)
    midweek_meeting_day = models.IntegerField(choices=DAY_OF_WEEK, default=QUINTA,
                                              verbose_name='Dia da reunião de meio de semana', null=True)
    weekend_meeting_day = models.IntegerField(choices=DAY_OF_WEEK, default=DOMINGO,
                                              verbose_name='Dia da reunião de fim de semana', null=True)
    host = models.BooleanField(default=False, verbose_name='Congregação Anfitriã')
    random_key = models.CharField(max_length=50, unique=True, null=True)

    objects = CongregationQuerySet.as_manager()


    def get_lpw_update_url(self):
        return reverse_lazy("lpw-congregation-update", kwargs={"pk": self.id})

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'congregação'
        verbose_name_plural = 'congregações'


class Person(models.Model):
    MASCULINO = 0
    FEMININO = 1

    GENDER = (
        (MASCULINO, 'Masculino'),
        (FEMININO, 'Feminino'),
    )


    ANCIAO = 0
    SERVO_MINISTERIAL = 1
    SEM_PRIVILEGIO_ESPECIAL = 2

    PRIVILEGE = (
        (ANCIAO, 'Ancião'),
        (SERVO_MINISTERIAL, 'Servo Ministerial'),
        (SEM_PRIVILEGIO_ESPECIAL, 'Sem privilégio especial'),
    )


    PIONEIRO_ESPECIAL = 0
    PIONEIRO_REGULAR = 1
    PIONEIRO_AUXILIAR = 2
    PUBLICADOR = 3

    MODALITY = (
        (PIONEIRO_ESPECIAL, 'Pioneiro Especial'),
        (PIONEIRO_REGULAR, 'Pioneiro Regular'),
        (PIONEIRO_AUXILIAR, 'Pioneiro Auxiliar'),
        (PUBLICADOR, 'Publicador'),
    )

    full_name = models.CharField(max_length=50, null=True, verbose_name='Nome completo')
    telephone = models.CharField(max_length=16, blank=True, verbose_name='Telefone')
    gender = models.IntegerField(choices=GENDER, default=MASCULINO, verbose_name='Sexo')
    privilege = models.IntegerField(choices=PRIVILEGE, default=SEM_PRIVILEGIO_ESPECIAL, verbose_name='Privilégio especial')
    modality = models.IntegerField(choices=MODALITY, default=PUBLICADOR, verbose_name='Ministério')
    watchtower_reader = models.BooleanField(default=False, verbose_name='Leitor de A Sentinela')
    bible_study_reader = models.BooleanField(default=False, verbose_name='Leitor de Estudo Bíblico')
    indicator = models.BooleanField(default=False, verbose_name='Indicador')
    mic = models.BooleanField(default=False, verbose_name='Microfone')
    note_sound_table = models.BooleanField(default=False, verbose_name='Notebook/Mesa de Som')
    zoom_indicator = models.BooleanField(default=False, verbose_name='Indicador Zoom')
    weekend_meeting_president = models.BooleanField(default=False, verbose_name='Presidente - Reunião de fim de semana')
    midweek_meeting_president = models.BooleanField(default=False, verbose_name='Presidente - Reunião de meio de semana')
    student_parts = models.BooleanField(default=True, verbose_name='Partes de Estudante')
    congregation = models.ForeignKey(Congregation, on_delete=models.PROTECT, null=True)

    def get_lpw_update_url(self):
        return reverse_lazy("lpw-person-update", kwargs={"pk": self.id})

    def get_update_url(self):
        return reverse_lazy("person-update", kwargs={"pk": self.id})

    def get_delete_url(self):
        return reverse_lazy("person-delete", kwargs={"pk": self.id})

    @property
    def indicators(self):
        return Meeting.objects.filter(Q(indicator_1=self) | Q(indicator_2=self))

    @property
    def mics(self):
        return Meeting.objects.filter(Q(mic_1=self) | Q(mic_2=self))

    def __str__(self):
        return f'{self.full_name}'

    objects = PersonQuerySet.as_manager()

    class Meta:
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'
        constraints = [UniqueConstraint(fields=['full_name', 'congregation'], name='unique_full_name_per_congregation')]


class PublicAssignment(models.Model):
    speech = models.ForeignKey(Speech, on_delete=models.PROTECT, null=True, verbose_name='Discurso', blank=True)
    speaker = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, verbose_name='Orador', blank=True)

    def get_update_url(self):
        return reverse_lazy('public-assignment-update', kwargs={"pk": self.id})

    def get_delete_url(self):
        return reverse_lazy("public-assignment-delete", kwargs={"pk": self.id})

    def __str__(self):
        return f'Designação pública - {self.speech} - {self.speaker}'

    class Meta:
        verbose_name = 'designação pública'
        verbose_name_plural = 'designações públicas'


class Meeting(models.Model):
    MIDWEEK = 0
    WEEKEND = 1

    MEETING_TYPE = (
        (MIDWEEK, 'Meio de semana'),
        (WEEKEND, 'Fim de semana'),
    )

    type = models.IntegerField(choices=MEETING_TYPE, default=MIDWEEK, verbose_name='Tipo de Reunião')
    date = models.DateField(verbose_name='Data')
    week = models.CharField(max_length=30, null=True, verbose_name='Semana')
    weekly_reading = models.CharField(max_length=30, null=True, verbose_name='Leitura Semanal')
    initial_song = models.CharField(max_length=30, null=True, verbose_name='Cântico inicial')
    middle_song = models.CharField(max_length=30, null=True, verbose_name='Cântico do meio')
    final_song = models.CharField(max_length=30, null=True, verbose_name='Cântico final')
    president = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, verbose_name='Presidente', blank=True)
    indicator_1 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Indicador 1', blank=True)
    indicator_2 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Indicador 2', blank=True)
    mic_1 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Microfone 1', blank=True)
    mic_2 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Microfone 2', blank=True)
    note_sound_table = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='audio_video_operator', verbose_name='Notebook/mesa de som', blank=True)
    zoom_indicator = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='audio_video_indicator', verbose_name='Indicador Zoom', blank=True)
    congregation = models.ForeignKey(Congregation, on_delete=models.CASCADE, verbose_name='Congregação')

    # as partes (relação ManyToMany) foram definidas na classe Parts

    # atributos específicos de reunião de fim de semana
    watchtower_ruling = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Dirigente de A Sentinela')
    watchtower_reader = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Leitor de A Sentinela')
    #reader_bible_study = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Leitor do Estudo Bíblico')
    public_assignment = models.ForeignKey(PublicAssignment, on_delete=models.CASCADE, null=True, verbose_name='Designação Pública')

    objects = MeetingQuerySet.as_manager()

    def __str__(self):
        return f'[{self.date}] - Reunião de {self.MEETING_TYPE[self.type][1]}'

    def get_update_url(self):
        return reverse_lazy('mechanical-privileges-update', kwargs={"pk": self.id})

    def get_watchtower_reader_update_url(self):
        return reverse_lazy('watchtower-reader-update', kwargs={"pk": self.id})

    def is_midweek_meeting(self):
        return self.type == Meeting.MIDWEEK

    def is_weekend_meeting(self):
        return self.type == Meeting.WEEKEND

    def set_songs(self, songs):
        if len(songs) == 3:
            self.initial_song = songs[0]
            self.middle_song = songs[1]
            self.final_song = songs[2]

    class Meta:
        verbose_name = 'reunião'
        verbose_name_plural = 'reuniões'
        constraints = [UniqueConstraint(fields=['date', 'congregation'], name='unique_meeting_per_congregation')]

jwcm/core/forms.py
from django import forms
from jwcm.core.models import Congregation
from django.forms import Form, ModelForm


class CongregationForm(ModelForm):
    class Meta:
        model = Congregation
        fields = ['name', 'number', 'midweek_meeting_time', 'weekend_meeting_time', 'midweek_meeting_day', 'weekend_meeting_day']


class BatchPersonForm(Form):
    file = forms.FileField(label='Arquivo')

jwcm/core/templates/core/batch_person.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block menu_items %}
    {% include 'core/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>{{ title }}</h3>
<hr>
    <p>Para cadastrar vários publicadores, carregue uma planilha (.csv, .xlsx, .xls, dentre outros formatos válidos) que siga o seguinte padrão:</p>
    <div class="table responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Telefone</th>
                <th>Sexo</th>
                <th>Privilegio</th>
                <th>Ministério</th>
                <th>Leitor de A Sentinela</th>
                <th>Leitor do Estudo Bíblico</th>
                <th>Indicador</th>
                <th>Microfone</th>
                <th>Faz partes de estudante</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>Roberto</td>
                <td>27 3318 4455</td>
                <td>Masculino</td>
                <td>Servo Ministerial</td>
                <td>Publicador</td>
                <td>Não</td>
                <td>Sim</td>
                <td>Sim</td>
                <td>Sim</td>
                <td>Sim</td>
            </tr>
            <tr>
                <td>Roberta</td>
                <td>27 3318 4455</td>
                <td>Feminino</td>
                <td>Sem privilégio especial</td>
                <td>Pioneiro regular</td>
                <td>Não</td>
                <td>Sim</td>
                <td>Não</td>
                <td>Sim</td>
                <td>Sim</td>
            </tr>
        </tbody>
    </table>
</div>

<form method="POST" id="form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-success mt-3">
        <i class="fas fa-check"></i> {{ button }}
    </button>
</form>
{% endblock %}

jwcm/core/templates/core/bulletin_board.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}


{% block menu_items %}
    {% include 'core/menu_items.html' %}
{% endblock %}


{% block content%}
<h3>{{ title }}</h3>
<hr>
<form method="POST" id="form">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-info mt-3" name="mechanical_privileges">
         {{ button_mechanical_privileges }}
    </button>
    <button type="submit" class="btn btn-info mt-3" name="student_parts">
         {{ button_student_parts }}
    </button>
    <button type="submit" class="btn btn-info mt-3" name="midweek_meeting">
         {{ button_midweek_meeting }}
    </button>
    <button type="submit" class="btn btn-info mt-3" name="weekend_meeting">
         {{ button_weekend_meeting }}
    </button>
</form>
{% endblock %}


{% block scripts %}
<script>
    $(document).ready(function(){

        $('#id_speech').select2();

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },

        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('#id_telephone').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock %}

jwcm/core/templates/core/congregation_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}


{% block menu_items %}
    {% include 'core/menu_items.html' %}
{% endblock %}


{% block content%}
<h3>{{ title }}</h3>
<hr>
<form method="POST" id="form">
    {% csrf_token %}
    {{ form|crispy }}

    <a href="{{congregation.congregationavailability.get_update_url}}" class="btn btn-warning" title="TPL">TPL <i class="fas fa-pencil"></i></a>
    <br>

    <button type="submit" class="btn btn-success mt-3">
        <i class="fas fa-check"></i> {{ button }}
    </button>
</form>
{% endblock %}


{% block scripts %}
<script>
    $(document).ready(function(){

        $('#id_speech').select2();

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },

        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('#id_telephone').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock %}

jwcm/core/templates/core/form_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block menu_items %}
    {% include 'core/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>{{ title }}</h3>
<hr>
<form method="POST" id="form">
    {% csrf_token %}
    Deseja mesmo excluir <strong>{{ object }}</strong> ? <br><br>

    <button type="submit" class="btn btn-danger mt-3">
        <i class="fas fa-trash-alt"></i> {{ button }}
    </button>


</form>
{% endblock %}

jwcm/core/templates/core/list_person.html
{% extends "base.html" %}
{% block title %}Publicadores{% endblock %}

{% block content%}
<h3>Publicadores da Congregação</h3>

<hr>
<a href="{% url 'person-create' %}" class="btn btn-primary">
    <i class="fas fa-plus"></i> Cadastrar
</a>
<a href="{% url 'person-batch-create' %}" class="btn btn-secondary">
    <i class="fas fa-plus"></i> Cadastrar em lote
</a>
<br><br>


<div class="table responsive">
    <table class="table table-striped" id="table-person">
        <thead>
            <tr>                
                <th>Nome</th>
                <th>Privilégio</th>                
                <th>Modalidade</th>
                <th>Partes de Estudante</th>
                <th>Leitor</th>
                <th>Indicador/Microfone</th>
                <th>Opções</th>
            </tr>
        </thead>

        <tbody>
            {% for person in object_list %}
            <tr>                
                <td> {{ person.full_name }} </td>
                <td> {{ person.get_privilege_display }} </td>
                <td> {{ person.get_modality_display }} </td>
                <td> {{ person.student_parts|yesno:'Sim,Não' }} </td>
                <td> {{ person.reader|yesno:'Sim,Não' }} </td>
                <td> {{ person.indicator_mic|yesno:'Sim,Não' }} </td>
                <td>
                    <a href="{{person.get_update_url}}" class="btn btn-warning" title="Editar">
                        <i class="fas fa-pencil"></i>
                    </a>
                    <a href="{{person.get_delete_url}}" class="btn btn-danger" title="Excluir">
                        <i class="fas fa-trash-can"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td>Nenhum registro.</tD>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}


{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table-person').DataTable({
            responsive: true,
            // "bSort": false,
            "aaSorting": [[0, "asc"]],
            "pageLength": 50,
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registos no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "A carregar dados...",
                "processing": "A processar...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            }
        });
    });
</script>
{% endblock %}

jwcm/core/templates/core/mechanical_privileges.html
{% extends "base.html" %}
{% block title %}Privilégios mecânicos{% endblock %}



{% block content%}
<h3>Privilégios mecânicos</h3>
<hr>

<div class="table responsive">
    <table class="table table-striped" id="table-mechanical-privileges">
        <thead>
            <tr>
                <th>Data</th>
                <th>Tipo</th>
                <th>Presidente</th>
                <th>Indicador 1</th>
                <th>Indicador 2</th>
                <th>Microfone 1</th>
                <th>Microfone 2</th>
                <th>Notebook/Mesa de som</th>
                <th>Opções</th>
            </tr>
        </thead>

        <tbody>
            {% for meeting in object_list %}
            <tr>
                <td> {{ meeting.date|date:"Y/m/d" }} </td>
                <td> {{ meeting.get_type_display }} </td>
                <td> {{ meeting.president }} </td>
                <td> {{ meeting.indicator_1 }} </td>
                <td> {{ meeting.indicator_2 }} </td>
                <td> {{ meeting.mic_1 }} </td>
                <td> {{ meeting.mic_2 }} </td>
                <td> {{ meeting.note_sound_table }} </td>

                <td>
                    <a href="{{meeting.get_update_url}}" class="btn btn-warning" title="Editar">
                        <i class="fas fa-pencil"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td>Nenhum registro.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}


{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table-mechanical-privileges').DataTable({
            responsive: true,
            // "bSort": false,
            "aaSorting": [[0, "asc"]],
            "pageLength": 50,
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registos no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "A carregar dados...",
                "processing": "A processar...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            }
        });
    });
</script>
{% endblock %}

jwcm/core/templates/core/mechanical_todo.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}


{% block content%}
<h3>{{ title }}</h3>
<hr>
<form method="POST" id="form">
    {% csrf_token %}
    {{ form|crispy }}

    {{ meetings }}

    <button type="submit" class="btn btn-info mt-3" name="search">
         {{ button_search }}
    </button>

</form>
{% endblock %}


{% block scripts %}
<script>
    $(document).ready(function(){

        $('#id_speech').select2();

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },

        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('#id_telephone').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock %}

jwcm/core/templates/core/menu_items.html
<li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'congregation' user.profile.congregation.pk %}">Congregação</a>
</li>
<li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'person-list' %}">Publicadores</a>
</li>

jwcm/core/templates/core/person_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}


{% block menu_items %}
    {% include 'core/menu_items.html' %}
{% endblock %}


{% block content%}
<h3>{{ title }}</h3>
<hr>
<form method="POST" id="form">
    {% csrf_token %}
    {{ form|crispy }}

    <a href="{{person.get_lpw_update_url}}" class="btn btn-warning" title="Disponibilidade TPL">Disponibilidade TPL <i class="fas fa-pencil"></i></a>
    <br>

    <button type="submit" class="btn btn-success mt-3">
        <i class="fas fa-check"></i> {{ button }}
    </button>
</form>
{% endblock %}


{% block scripts %}
<script>
    $(document).ready(function(){

        $('#id_speech').select2();

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },

        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('#id_telephone').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock %}