jwcm/life_and_ministry/urls.py
from django.urls import path
from jwcm.life_and_ministry.views import PartListView, AssignmentListView, PartUpdate, AssignmentUpdate


urlpatterns = [
    path('part/', PartListView.as_view(), name='part-list'),
    path('part/update/<int:pk>/', PartUpdate.as_view(), name='part-update'),

    path('assignment/', AssignmentListView.as_view(), name='assignment-list'),
    path('assignment/update/<int:pk>/', AssignmentUpdate.as_view(), name='assignment-update'),
]

jwcm/urls.py
from django.contrib import admin
from django.urls import path, include
from jwcm.core.views import About, CongregationUpdate, PersonList, PersonCreate, \
    PersonUpdate, PersonDelete, person_batch_create, home, \
    MechanicalPrivilegesListView, MechanicalPrivilegesUpdateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('public_speeches/', include('jwcm.public_speeches.urls')),
    path('life_and_ministry/', include('jwcm.life_and_ministry.urls')),
    path('users/', include('jwcm.users.urls')),
    path('lpw/', include('jwcm.lpw.urls')),
    path('reports/', include('jwcm.reports.urls')),

    path('', home, name='home'),
    path('about/', About.as_view(), name='about'),

    path('congregation/<int:pk>/', CongregationUpdate.as_view(), name='congregation'),

    path('person/', PersonList.as_view(), name='person-list'),
    path('person/create/', PersonCreate.as_view(), name='person-create'),
    path('person/update/<int:pk>/', PersonUpdate.as_view(), name='person-update'),
    path('person/delete/<int:pk>/', PersonDelete.as_view(), name='person-delete'),
    path('person/create/batch/', person_batch_create, name='person-batch-create'),

    path('mechanical_privileges/', MechanicalPrivilegesListView.as_view(), name='mechanical-privileges-list'),
    path('mechanical_privileges/<int:pk>/', MechanicalPrivilegesUpdateView.as_view(), name='mechanical-privileges-update'),


]

jwcm/core/models.py
from django.db.models import Q, UniqueConstraint
from django.db import models
from datetime import time
from django.urls import reverse_lazy
from jwcm.core.managers import PersonQuerySet, MeetingQuerySet, CongregationQuerySet
from jwcm.public_speeches.models import Speech


class Congregation(models.Model):
    SEGUNDA = 0
    TERCA = 1
    QUARTA = 2
    QUINTA = 3
    SEXTA = 4
    SABADO = 5
    DOMINGO = 6

    DAY_OF_WEEK = (
        (SEGUNDA, 'Segunda-feira'),
        (TERCA, 'Terça-feira'),
        (QUARTA, 'Quarta-feira'),
        (QUINTA, 'Quinta-feira'),
        (SEXTA, 'Sexta-feira'),
        (SABADO, 'Sábado'),
        (DOMINGO, 'Domingo'),
    )

    name = models.CharField(max_length=50, verbose_name='Nome')
    number = models.IntegerField(unique=True, verbose_name='Número', null=True)
    midweek_meeting_time = models.TimeField(verbose_name='Horário da reunião de meio de semana',
                                            default=time(19, 30, 00), null=True)
    weekend_meeting_time = models.TimeField(verbose_name='Horário da reunião de fim de semana',
                                            default=time(18, 00, 00), null=True)
    midweek_meeting_day = models.IntegerField(choices=DAY_OF_WEEK, default=QUINTA,
                                              verbose_name='Dia da reunião de meio de semana', null=True)
    weekend_meeting_day = models.IntegerField(choices=DAY_OF_WEEK, default=DOMINGO,
                                              verbose_name='Dia da reunião de fim de semana', null=True)
    host = models.BooleanField(default=False, verbose_name='Congregação Anfitriã')
    random_key = models.CharField(max_length=50, unique=True, null=True)

    objects = CongregationQuerySet.as_manager()


    def get_lpw_update_url(self):
        return reverse_lazy("lpw-congregation-update", kwargs={"pk": self.id})

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'congregação'
        verbose_name_plural = 'congregações'


class Person(models.Model):
    MASCULINO = 0
    FEMININO = 1

    GENDER = (
        (MASCULINO, 'Masculino'),
        (FEMININO, 'Feminino'),
    )


    ANCIAO = 0
    SERVO_MINISTERIAL = 1
    SEM_PRIVILEGIO_ESPECIAL = 2

    PRIVILEGE = (
        (ANCIAO, 'Ancião'),
        (SERVO_MINISTERIAL, 'Servo Ministerial'),
        (SEM_PRIVILEGIO_ESPECIAL, 'Sem privilégio especial'),
    )


    PIONEIRO_ESPECIAL = 0
    PIONEIRO_REGULAR = 1
    PIONEIRO_AUXILIAR = 2
    PUBLICADOR = 3

    MODALITY = (
        (PIONEIRO_ESPECIAL, 'Pioneiro Especial'),
        (PIONEIRO_REGULAR, 'Pioneiro Regular'),
        (PIONEIRO_AUXILIAR, 'Pioneiro Auxiliar'),
        (PUBLICADOR, 'Publicador'),
    )

    full_name = models.CharField(max_length=50, null=True, verbose_name='Nome completo')
    telephone = models.CharField(max_length=16, blank=True, verbose_name='Telefone')
    gender = models.IntegerField(choices=GENDER, default=MASCULINO, verbose_name='Sexo')
    privilege = models.IntegerField(choices=PRIVILEGE, default=SEM_PRIVILEGIO_ESPECIAL, verbose_name='Privilégio especial')
    modality = models.IntegerField(choices=MODALITY, default=PUBLICADOR, verbose_name='Ministério')
    watchtower_reader = models.BooleanField(default=False, verbose_name='Leitor de A Sentinela')
    bible_study_reader = models.BooleanField(default=False, verbose_name='Leitor de Estudo Bíblico')
    indicator = models.BooleanField(default=False, verbose_name='Indicador')
    mic = models.BooleanField(default=False, verbose_name='Microfone')
    note_sound_table = models.BooleanField(default=False, verbose_name='Notebook/Mesa de Som')
    zoom_indicator = models.BooleanField(default=False, verbose_name='Indicador Zoom')
    weekend_meeting_president = models.BooleanField(default=False, verbose_name='Presidente - Reunião de fim de semana')
    midweek_meeting_president = models.BooleanField(default=False, verbose_name='Presidente - Reunião de meio de semana')
    student_parts = models.BooleanField(default=True, verbose_name='Partes de Estudante')
    congregation = models.ForeignKey(Congregation, on_delete=models.PROTECT, null=True)

    def get_lpw_update_url(self):
        return reverse_lazy("lpw-person-update", kwargs={"pk": self.id})

    def get_update_url(self):
        return reverse_lazy("person-update", kwargs={"pk": self.id})

    def get_delete_url(self):
        return reverse_lazy("person-delete", kwargs={"pk": self.id})

    @property
    def indicators(self):
        return Meeting.objects.filter(Q(indicator_1=self) | Q(indicator_2=self))

    @property
    def mics(self):
        return Meeting.objects.filter(Q(mic_1=self) | Q(mic_2=self))

    def __str__(self):
        return f'{self.full_name}'

    objects = PersonQuerySet.as_manager()

    class Meta:
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'
        constraints = [UniqueConstraint(fields=['full_name', 'congregation'], name='unique_full_name_per_congregation')]


class PublicAssignment(models.Model):
    speech = models.ForeignKey(Speech, on_delete=models.PROTECT, null=True, verbose_name='Discurso', blank=True)
    speaker = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, verbose_name='Orador', blank=True)

    def get_update_url(self):
        return reverse_lazy('public-assignment-update', kwargs={"pk": self.id})

    def get_delete_url(self):
        return reverse_lazy("public-assignment-delete", kwargs={"pk": self.id})

    def __str__(self):
        return f'Designação pública - {self.speech} - {self.speaker}'

    class Meta:
        verbose_name = 'designação pública'
        verbose_name_plural = 'designações públicas'


class Meeting(models.Model):
    MIDWEEK = 0
    WEEKEND = 1

    MEETING_TYPE = (
        (MIDWEEK, 'Meio de semana'),
        (WEEKEND, 'Fim de semana'),
    )

    type = models.IntegerField(choices=MEETING_TYPE, default=MIDWEEK, verbose_name='Tipo de Reunião')
    date = models.DateField(verbose_name='Data')
    week = models.CharField(max_length=30, null=True, verbose_name='Semana')
    weekly_reading = models.CharField(max_length=30, null=True, verbose_name='Leitura Semanal')
    initial_song = models.CharField(max_length=30, null=True, verbose_name='Cântico inicial')
    middle_song = models.CharField(max_length=30, null=True, verbose_name='Cântico do meio')
    final_song = models.CharField(max_length=30, null=True, verbose_name='Cântico final')
    president = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, verbose_name='Presidente', blank=True)
    indicator_1 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Indicador 1', blank=True)
    indicator_2 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Indicador 2', blank=True)
    mic_1 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Microfone 1', blank=True)
    mic_2 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Microfone 2', blank=True)
    note_sound_table = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='audio_video_operator', verbose_name='Notebook/mesa de som', blank=True)
    zoom_indicator = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='audio_video_indicator', verbose_name='Indicador Zoom', blank=True)
    congregation = models.ForeignKey(Congregation, on_delete=models.CASCADE, verbose_name='Congregação')

    # as partes (relação ManyToMany) foram definidas na classe Parts

    # atributos específicos de reunião de fim de semana
    watchtower_ruling = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Dirigente de A Sentinela')
    watchtower_reader = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Leitor de A Sentinela')
    #reader_bible_study = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Leitor do Estudo Bíblico')
    public_assignment = models.ForeignKey(PublicAssignment, on_delete=models.CASCADE, null=True, verbose_name='Designação Pública')

    objects = MeetingQuerySet.as_manager()

    def __str__(self):
        return f'[{self.date}] - Reunião de {self.MEETING_TYPE[self.type][1]}'

    def get_update_url(self):
        return reverse_lazy('mechanical-privileges-update', kwargs={"pk": self.id})

    def get_watchtower_reader_update_url(self):
        return reverse_lazy('watchtower-reader-update', kwargs={"pk": self.id})

    def is_midweek_meeting(self):
        return self.type == Meeting.MIDWEEK

    def is_weekend_meeting(self):
        return self.type == Meeting.WEEKEND

    def set_songs(self, songs):
        if len(songs) == 3:
            self.initial_song = songs[0]
            self.middle_song = songs[1]
            self.final_song = songs[2]

    class Meta:
        verbose_name = 'reunião'
        verbose_name_plural = 'reuniões'
        constraints = [UniqueConstraint(fields=['date', 'congregation'], name='unique_meeting_per_congregation')]

jwcm/life_and_ministry/models.py
from django.db import models
from django.urls import reverse_lazy
from jwcm.core.models import Person, Meeting
from datetime import datetime
from jwcm.life_and_ministry.managers import PartQuerySet



class Part(models.Model):
    TESOUROS_DA_PALAVRA_DE_DEUS = 0
    FACA_SEU_MELHOR_NO_MINISTÉRIO = 1
    NOSSA_VIDA_CRISTA = 2

    SECTION = (
        (TESOUROS_DA_PALAVRA_DE_DEUS, 'Tesouros da Palavra de Deus'),
        (FACA_SEU_MELHOR_NO_MINISTÉRIO, 'Faça seu melhor no ministério'),
        (NOSSA_VIDA_CRISTA, 'Nossa vida cristã'),
    )

    section = models.IntegerField(choices=SECTION, default=TESOUROS_DA_PALAVRA_DE_DEUS, verbose_name='Seção')
    theme = models.TextField(verbose_name='Tema')
    date = models.DateField(verbose_name='Data', default=datetime.now)

    objects = PartQuerySet.as_manager()

    def __str__(self):
        return f'{self.date.strftime("%d/%m/%Y")} - [{self.SECTION[self.section][1]}] - {self.theme}'

    def get_update_url(self):
        return reverse_lazy("part-update", kwargs={"pk": self.id})

    class Meta:
        verbose_name = 'parte'
        verbose_name_plural = 'partes'


class LifeAndMinistryAssignment(models.Model):
    part = models.ForeignKey(Part, on_delete=models.CASCADE, verbose_name='Parte')
    owner = models.ForeignKey(Person, verbose_name='Dono da parte',
                                  on_delete=models.PROTECT, null=True, related_name='owner', blank=True)
    assistant = models.ForeignKey(Person, verbose_name='Ajudante',
                                  on_delete=models.PROTECT, null=True,
                                  related_name='helper', blank=True)
    meeting = models.ManyToManyField(Meeting, verbose_name='Reunião')

    def __str__(self):
        return f'Designação: {self.owner} {self.part.theme}'

    def get_update_url(self):
        return reverse_lazy("assignment-update", kwargs={"pk": self.id})

    class Meta:
        verbose_name = 'Designação da reunião Vida e Ministério'
        verbose_name_plural = 'Designações da reunião Vida e Ministério'

jwcm/life_and_ministry/templates/life_and_ministry/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}


{% block menu_items %}
    {% include 'life_and_ministry/menu_items.html' %}
{% endblock %}


{% block content%}
<h3>{{ title }}</h3>
<hr>
<form method="POST" id="form">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-success mt-3">
        <i class="fas fa-check"></i> {{ button }}
    </button>
</form>
{% endblock %}


{% block scripts %}
<script>
    $(document).ready(function(){

        $('#id_speech').select2();

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },

        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('#id_telephone').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock %}

jwcm/life_and_ministry/templates/life_and_ministry/list_assignment.html
{% extends "base.html" %}
{% block title %}Designações da Reunião Vida e Ministério{% endblock %}


{% block content%}
<h3>Designações</h3>


<hr>
<br><br>


<div class="table responsive">
    <table class="table table-striped" id="table-assignment">
        <thead>
            <tr>
                <th>Data</th>
                <th>Tema</th>
                <th>Publicador</th>
                <th>Ajudante</th>
                <th>Opções</th>
            </tr>
        </thead>

        <tbody>
            {% for assignment in object_list %}
            <tr>                
                <td> {{ assignment.part.date|date:"Y/m/d" }} </td>
                <td> {{ assignment.part.theme }}  [{{ assignment.part.get_section_display }}] </td>
                <td> {{ assignment.owner }} </td>
                <td> {{ assignment.assistant }} </td>
                <td>
                    <a href="{{assignment.get_update_url}}" class="btn btn-warning" title="Editar">
                        <i class="fas fa-pencil"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td>Nenhum registro.</tD>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}


{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table-assignment').DataTable({
            responsive: true,
            // "bSort": false,
            "aaSorting": [[0, "asc"]],
            "pageLength": 50,
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registos no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "A carregar dados...",
                "processing": "A processar...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            }
        });
    });
</script>
{% endblock %}

jwcm/life_and_ministry/templates/life_and_ministry/list_part.html
{% extends "base.html" %}
{% block title %}Partes da Reunião Vida e Ministério{% endblock %}

{% block menu_items %}
    {% include 'life_and_ministry/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>Partes</h3>


<hr>
<br><br>


<div class="table responsive">
    <table class="table table-striped" id="table-part">
        <thead>
            <tr>
                <th>Data</th>
                <th>Tema</th>
                <th>Seção</th>
                <th>Opções</th>
            </tr>
        </thead>

        <tbody>
            {% for part in object_list %}
            <tr>                
                <td> {{ part.date|date:"Y/m/d" }} </td>
                <td> {{ part.theme }} </td>
                <td> {{ part.get_section_display }} </td>
                <td>
                    <a href="{{part.get_update_url}}" class="btn btn-warning" title="Editar">
                        <i class="fas fa-pencil"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td>Nenhum registro.</tD>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}


{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table-part').DataTable({
            responsive: true,
            // "bSort": false,
            "aaSorting": [[0, "asc"]],
            "pageLength": 50,
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registos no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "A carregar dados...",
                "processing": "A processar...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            }
        });
    });
</script>
{% endblock %}

jwcm/life_and_ministry/templates/life_and_ministry/menu_items.html
{% if request.user.is_superuser %}
<li class="nav-item">
	<a class="nav-link active" aria-current="page" href="{% url 'part-list' %}">Partes</a>
</li>
{% endif %}
<li class="nav-item">
	<a class="nav-link active" aria-current="page" href="{% url 'assignment-list' %}">Designações</a>
</li>