jwcm/public_speeches/urls.py
from django.urls import path

from jwcm.public_speeches.views import SpeechList, SpeechCreate, SpeechUpdate, SpeechDelete, PublicAssignmentList, \
    public_assignment_create, public_assignment_update, PublicAssignmentDelete, person_guest_create, \
    congregation_guest_pop_up_create, WatchtowerReadertList, WatchtowerReaderUpdate

urlpatterns = [
    path('speech/', SpeechList.as_view(), name='speech-list'),
    path('speech/create/', SpeechCreate.as_view(), name='speech-create'),
    path('speech/update/<int:pk>/', SpeechUpdate.as_view(), name='speech-update'),
    path('speech/delete/<int:pk>/', SpeechDelete.as_view(), name='speech-delete'),

    path('public_assignment/', PublicAssignmentList.as_view(), name='public-assignment-list'),
    path('public_assignment/create/', public_assignment_create, name='public-assignment-create'),
    path('public_assignment/update/<int:pk>/', public_assignment_update, name='public-assignment-update'),
    path('public_assignment/delete/<int:pk>/', PublicAssignmentDelete.as_view(), name='public-assignment-delete'),

    path('person_guest/create/', person_guest_create, name ='person-guest-create'),
    path('congregation_guest/create/', congregation_guest_pop_up_create, name ='congregation-guest-create'),

    path('watchtower_reader/', WatchtowerReadertList.as_view(), name='watchtower-reader-list'),
    path('watchtower_reader/update/<int:pk>/', WatchtowerReaderUpdate.as_view(), name='watchtower-reader-update'),
]

jwcm/urls.py
from django.contrib import admin
from django.urls import path, include
from jwcm.core.views import About, CongregationUpdate, PersonList, PersonCreate, \
    PersonUpdate, PersonDelete, person_batch_create, home, \
    MechanicalPrivilegesListView, MechanicalPrivilegesUpdateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('public_speeches/', include('jwcm.public_speeches.urls')),
    path('life_and_ministry/', include('jwcm.life_and_ministry.urls')),
    path('users/', include('jwcm.users.urls')),
    path('lpw/', include('jwcm.lpw.urls')),
    path('reports/', include('jwcm.reports.urls')),

    path('', home, name='home'),
    path('about/', About.as_view(), name='about'),

    path('congregation/<int:pk>/', CongregationUpdate.as_view(), name='congregation'),

    path('person/', PersonList.as_view(), name='person-list'),
    path('person/create/', PersonCreate.as_view(), name='person-create'),
    path('person/update/<int:pk>/', PersonUpdate.as_view(), name='person-update'),
    path('person/delete/<int:pk>/', PersonDelete.as_view(), name='person-delete'),
    path('person/create/batch/', person_batch_create, name='person-batch-create'),

    path('mechanical_privileges/', MechanicalPrivilegesListView.as_view(), name='mechanical-privileges-list'),
    path('mechanical_privileges/<int:pk>/', MechanicalPrivilegesUpdateView.as_view(), name='mechanical-privileges-update'),


]

jwcm/core/models.py
from django.db.models import Q, UniqueConstraint
from django.db import models
from datetime import time
from django.urls import reverse_lazy
from jwcm.core.managers import PersonQuerySet, MeetingQuerySet, CongregationQuerySet
from jwcm.public_speeches.models import Speech


class Congregation(models.Model):
    SEGUNDA = 0
    TERCA = 1
    QUARTA = 2
    QUINTA = 3
    SEXTA = 4
    SABADO = 5
    DOMINGO = 6

    DAY_OF_WEEK = (
        (SEGUNDA, 'Segunda-feira'),
        (TERCA, 'Terça-feira'),
        (QUARTA, 'Quarta-feira'),
        (QUINTA, 'Quinta-feira'),
        (SEXTA, 'Sexta-feira'),
        (SABADO, 'Sábado'),
        (DOMINGO, 'Domingo'),
    )

    name = models.CharField(max_length=50, verbose_name='Nome')
    number = models.IntegerField(unique=True, verbose_name='Número', null=True)
    midweek_meeting_time = models.TimeField(verbose_name='Horário da reunião de meio de semana',
                                            default=time(19, 30, 00), null=True)
    weekend_meeting_time = models.TimeField(verbose_name='Horário da reunião de fim de semana',
                                            default=time(18, 00, 00), null=True)
    midweek_meeting_day = models.IntegerField(choices=DAY_OF_WEEK, default=QUINTA,
                                              verbose_name='Dia da reunião de meio de semana', null=True)
    weekend_meeting_day = models.IntegerField(choices=DAY_OF_WEEK, default=DOMINGO,
                                              verbose_name='Dia da reunião de fim de semana', null=True)
    host = models.BooleanField(default=False, verbose_name='Congregação Anfitriã')
    random_key = models.CharField(max_length=50, unique=True, null=True)

    objects = CongregationQuerySet.as_manager()


    def get_lpw_update_url(self):
        return reverse_lazy("lpw-congregation-update", kwargs={"pk": self.id})

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'congregação'
        verbose_name_plural = 'congregações'


class Person(models.Model):
    MASCULINO = 0
    FEMININO = 1

    GENDER = (
        (MASCULINO, 'Masculino'),
        (FEMININO, 'Feminino'),
    )


    ANCIAO = 0
    SERVO_MINISTERIAL = 1
    SEM_PRIVILEGIO_ESPECIAL = 2

    PRIVILEGE = (
        (ANCIAO, 'Ancião'),
        (SERVO_MINISTERIAL, 'Servo Ministerial'),
        (SEM_PRIVILEGIO_ESPECIAL, 'Sem privilégio especial'),
    )


    PIONEIRO_ESPECIAL = 0
    PIONEIRO_REGULAR = 1
    PIONEIRO_AUXILIAR = 2
    PUBLICADOR = 3

    MODALITY = (
        (PIONEIRO_ESPECIAL, 'Pioneiro Especial'),
        (PIONEIRO_REGULAR, 'Pioneiro Regular'),
        (PIONEIRO_AUXILIAR, 'Pioneiro Auxiliar'),
        (PUBLICADOR, 'Publicador'),
    )

    full_name = models.CharField(max_length=50, null=True, verbose_name='Nome completo')
    telephone = models.CharField(max_length=16, blank=True, verbose_name='Telefone')
    gender = models.IntegerField(choices=GENDER, default=MASCULINO, verbose_name='Sexo')
    privilege = models.IntegerField(choices=PRIVILEGE, default=SEM_PRIVILEGIO_ESPECIAL, verbose_name='Privilégio especial')
    modality = models.IntegerField(choices=MODALITY, default=PUBLICADOR, verbose_name='Ministério')
    watchtower_reader = models.BooleanField(default=False, verbose_name='Leitor de A Sentinela')
    bible_study_reader = models.BooleanField(default=False, verbose_name='Leitor de Estudo Bíblico')
    indicator = models.BooleanField(default=False, verbose_name='Indicador')
    mic = models.BooleanField(default=False, verbose_name='Microfone')
    note_sound_table = models.BooleanField(default=False, verbose_name='Notebook/Mesa de Som')
    zoom_indicator = models.BooleanField(default=False, verbose_name='Indicador Zoom')
    weekend_meeting_president = models.BooleanField(default=False, verbose_name='Presidente - Reunião de fim de semana')
    midweek_meeting_president = models.BooleanField(default=False, verbose_name='Presidente - Reunião de meio de semana')
    student_parts = models.BooleanField(default=True, verbose_name='Partes de Estudante')
    congregation = models.ForeignKey(Congregation, on_delete=models.PROTECT, null=True)

    def get_lpw_update_url(self):
        return reverse_lazy("lpw-person-update", kwargs={"pk": self.id})

    def get_update_url(self):
        return reverse_lazy("person-update", kwargs={"pk": self.id})

    def get_delete_url(self):
        return reverse_lazy("person-delete", kwargs={"pk": self.id})

    @property
    def indicators(self):
        return Meeting.objects.filter(Q(indicator_1=self) | Q(indicator_2=self))

    @property
    def mics(self):
        return Meeting.objects.filter(Q(mic_1=self) | Q(mic_2=self))

    def __str__(self):
        return f'{self.full_name}'

    objects = PersonQuerySet.as_manager()

    class Meta:
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'
        constraints = [UniqueConstraint(fields=['full_name', 'congregation'], name='unique_full_name_per_congregation')]


class PublicAssignment(models.Model):
    speech = models.ForeignKey(Speech, on_delete=models.PROTECT, null=True, verbose_name='Discurso', blank=True)
    speaker = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, verbose_name='Orador', blank=True)

    def get_update_url(self):
        return reverse_lazy('public-assignment-update', kwargs={"pk": self.id})

    def get_delete_url(self):
        return reverse_lazy("public-assignment-delete", kwargs={"pk": self.id})

    def __str__(self):
        return f'Designação pública - {self.speech} - {self.speaker}'

    class Meta:
        verbose_name = 'designação pública'
        verbose_name_plural = 'designações públicas'


class Meeting(models.Model):
    MIDWEEK = 0
    WEEKEND = 1

    MEETING_TYPE = (
        (MIDWEEK, 'Meio de semana'),
        (WEEKEND, 'Fim de semana'),
    )

    type = models.IntegerField(choices=MEETING_TYPE, default=MIDWEEK, verbose_name='Tipo de Reunião')
    date = models.DateField(verbose_name='Data')
    week = models.CharField(max_length=30, null=True, verbose_name='Semana')
    weekly_reading = models.CharField(max_length=30, null=True, verbose_name='Leitura Semanal')
    initial_song = models.CharField(max_length=30, null=True, verbose_name='Cântico inicial')
    middle_song = models.CharField(max_length=30, null=True, verbose_name='Cântico do meio')
    final_song = models.CharField(max_length=30, null=True, verbose_name='Cântico final')
    president = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, verbose_name='Presidente', blank=True)
    indicator_1 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Indicador 1', blank=True)
    indicator_2 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Indicador 2', blank=True)
    mic_1 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Microfone 1', blank=True)
    mic_2 = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Microfone 2', blank=True)
    note_sound_table = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='audio_video_operator', verbose_name='Notebook/mesa de som', blank=True)
    zoom_indicator = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='audio_video_indicator', verbose_name='Indicador Zoom', blank=True)
    congregation = models.ForeignKey(Congregation, on_delete=models.CASCADE, verbose_name='Congregação')

    # as partes (relação ManyToMany) foram definidas na classe Parts

    # atributos específicos de reunião de fim de semana
    watchtower_ruling = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Dirigente de A Sentinela')
    watchtower_reader = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Leitor de A Sentinela')
    #reader_bible_study = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', verbose_name='Leitor do Estudo Bíblico')
    public_assignment = models.ForeignKey(PublicAssignment, on_delete=models.CASCADE, null=True, verbose_name='Designação Pública')

    objects = MeetingQuerySet.as_manager()

    def __str__(self):
        return f'[{self.date}] - Reunião de {self.MEETING_TYPE[self.type][1]}'

    def get_update_url(self):
        return reverse_lazy('mechanical-privileges-update', kwargs={"pk": self.id})

    def get_watchtower_reader_update_url(self):
        return reverse_lazy('watchtower-reader-update', kwargs={"pk": self.id})

    def is_midweek_meeting(self):
        return self.type == Meeting.MIDWEEK

    def is_weekend_meeting(self):
        return self.type == Meeting.WEEKEND

    def set_songs(self, songs):
        if len(songs) == 3:
            self.initial_song = songs[0]
            self.middle_song = songs[1]
            self.final_song = songs[2]

    class Meta:
        verbose_name = 'reunião'
        verbose_name_plural = 'reuniões'
        constraints = [UniqueConstraint(fields=['date', 'congregation'], name='unique_meeting_per_congregation')]

jwcm/lpw/models.py
from django.db import models
from django.urls import reverse_lazy
from jwcm.core.models import Person, Congregation
from jwcm.lpw.managers import DayLPWQuerySet


class Availability(models.Model):
    weekday = models.IntegerField(choices=Congregation.DAY_OF_WEEK, default=Congregation.DOMINGO, verbose_name='Dia da semana')
    morning = models.BooleanField(default=False, verbose_name='Manhã')
    afternoon = models.BooleanField(default=False, verbose_name='Tarde')
    night = models.BooleanField(default=False, verbose_name='Noite')

    class Meta:
        abstract = True


class PersonAvailability(Availability):
    person = models.ManyToManyField(Person, verbose_name='Disponibilidade')

    def get_update_url(self):
        return reverse_lazy("lpw-person-update", kwargs={"pk": self.id})

    def __str__(self):
        p = self.person.all()[0]
        return f'{p.full_name} - {Congregation.DAY_OF_WEEK[self.weekday][1]}'

    class Meta:
        verbose_name = 'Publicador - Disponibilidade TPL'
        verbose_name_plural = 'Publicadores - Disponibilidades TPL'


class CongregationAvailability(Availability):
    congregation = models.ManyToManyField(Congregation, verbose_name='Disponibilidade')

    def get_update_url(self):
        return reverse_lazy("lpw-congregation-update", kwargs={"pk": self.id})

    def __str__(self):
        c = self.congregation.all()[0]
        return f'{c.name} - {Congregation.DAY_OF_WEEK[self.weekday][1]}'

    class Meta:
        verbose_name = 'Congregação - Disponibilidade TPL'
        verbose_name_plural = 'Congregações - Disponibilidades TPL'


class DayLPW(models.Model):
    date = models.DateField(verbose_name='Data')
    weekday = models.IntegerField(choices=Congregation.DAY_OF_WEEK, verbose_name='Dia da semana')

    morning = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', blank=True, verbose_name='Manhã')
    morning_available = models.BooleanField(default=False, verbose_name='Disponibilidade - manhã')

    afternoon = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', blank=True, verbose_name='Tarde')
    afternoon_available = models.BooleanField(default=False, verbose_name='Disponibilidade - tarde')

    night = models.ForeignKey(Person, on_delete=models.PROTECT, null=True, related_name='+', blank=True, verbose_name='Noite')
    night_available = models.BooleanField(default=False, verbose_name='Disponibilidade - noite')

    congregation = models.ForeignKey(Congregation, on_delete=models.PROTECT, null=True)

    objects = DayLPWQuerySet.as_manager()

    def get_update_url(self):
        return reverse_lazy("lpw-congregation-update", kwargs={"pk": self.id})

    def __str__(self):
        return f'{self.date} ({self.congregation})'

    class Meta:
        verbose_name = 'Dia LPW'
        verbose_name_plural = 'Dias LPW'

jwcm/public_speeches/models.py
from django.db import models
from django.urls import reverse_lazy



class Speech(models.Model):
    number = models.IntegerField(unique=True, verbose_name='Número')
    theme = models.CharField(max_length=80, verbose_name='Tema')

    def __str__(self):
        return f'{self.number} - {self.theme}'

    class Meta:
        verbose_name = 'discurso'
        verbose_name_plural = 'discursos'

    def get_update_url(self):
        return reverse_lazy("speech-update", kwargs={"pk": self.id})

    def get_delete_url(self):
        return reverse_lazy("speech-delete", kwargs={"pk": self.id})

jwcm/public_speeches/forms.py
from django.db.models import Q
from django import forms
from jwcm.core.models import Person, Congregation, PublicAssignment
from jwcm.core.widget import DatePickerInput
from jwcm.public_speeches.models import Speech



class SpeechForm(forms.ModelForm):
    class Meta:
        model = Speech
        fields = ['number', 'theme']


class PublicAssignmentForm(forms.ModelForm):
    class Meta:
        model = PublicAssignment
        fields = ['speech', 'speaker']
        #widgets = {'date': DatePickerInput(format=('%Y-%m-%d'), attrs={}),} #adicionar o campo data novamente?

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(PublicAssignmentForm, self).__init__(*args, **kwargs)
        self.fields['speaker'].queryset = Person.objects.elders_and_ministerial_servants_per_congregation(self.request.user.profile.congregation)


class PersonGuestForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['full_name', 'telephone', 'congregation']


class CongregationGuestPopUpForm(forms.ModelForm):
    class Meta:
        model = Congregation
        fields = ['name']

jwcm/public_speeches/templates/public_speeches/congregation_guest.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block menu_items %}
    {% include 'public_speeches/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>{{ title }}</h3>
<hr>

<form method="POST" id="form">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-success mt-3">
        <i class="fas fa-check"></i> {{ button }}
    </button>
</form>
{% endblock %}
{% block scripts %}
<style>
    .navbar{
         visibility: hidden;
    }
</style>
{% endblock %}

jwcm/public_speeches/templates/public_speeches/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}


{% block menu_items %}
    {% include 'public_speeches/menu_items.html' %}
{% endblock %}


{% block content%}
<h3>{{ title }}</h3>
<hr>
<form method="POST" id="form">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-success mt-3">
        <i class="fas fa-check"></i> {{ button }}
    </button>
</form>
{% endblock %}


{% block scripts %}
<script>
    $(document).ready(function(){

        $('#id_speech').select2();

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },

        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('#id_telephone').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock %}

jwcm/public_speeches/templates/public_speeches/form_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block menu_items %}
    {% include 'public_speeches/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>{{ title }}</h3>
<hr>
<form method="POST" id="form">
    {% csrf_token %}
    Deseja mesmo excluir <strong>{{ object }}</strong> ? <br><br>

    <button type="submit" class="btn btn-danger mt-3">
        <i class="fas fa-trash-alt"></i> {{ button }}
    </button>


</form>
{% endblock %}

jwcm/public_speeches/templates/public_speeches/list_public_assignment.html
{% extends "base.html" %}
{% block title %}Arranjo de Oradores{% endblock %}

{% block menu_items %}
    {% include 'public_speeches/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>Arranjo de Oradores</h3>

<hr>
<!--a href="{% url 'public-assignment-create' %}" class="btn btn-primary">
    <i class="fas fa-plus"></i> Cadastrar
</a>
<br><br-->


<div class="table responsive">
    <table class="table table-striped" id="table-public-assignment">
        <thead>
            <tr>                
                <th>Data</th>
                <th>Discurso</th>
                <th>Orador</th>
                <th>Opções</th>
            </tr>
        </thead>

        <tbody>
            {% for meeting in object_list %}
            <tr>                
                <td> {{ meeting.date|date:"Y/m/d" }} </td>
                <td> {{ meeting.public_assignment.speech.theme }} ({{ meeting.public_assignment.speech.number }}) </td>
                <td> {{ meeting.public_assignment.speaker.full_name }} </td>
                <td>
                    <a href="{{meeting.public_assignment.get_update_url}}" class="btn btn-warning" title="Editar">
                        <i class="fas fa-pencil"></i>
                    </a>
                    <!--a href="{{meeting.public_assignment.get_delete_url}}" class="btn btn-danger" title="Excluir">
                        <i class="fas fa-trash-can"></i>
                    </a-->
                </td>
            </tr>
            {% empty %}
            <tr>
                <td>Nenhum registro.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}

{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table-public-assignment').DataTable({
            responsive: true,
            // "bSort": false,
            "aaSorting": [[0, "desc"]],
            "pageLength": 50,
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registos no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "A carregar dados...",
                "processing": "A processar...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            }
        });
    });
</script>
{% endblock %}

jwcm/public_speeches/templates/public_speeches/list_speech.html
{% extends "base.html" %}
{% block title %}Discursos Públicos{% endblock %}

{% block menu_items %}
    {% include 'public_speeches/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>Discursos Públicos</h3>

<hr>
<a href="{% url 'speech-create' %}" class="btn btn-primary">
    <i class="fas fa-plus"></i> Cadastrar
</a>
<br><br>


<div class="table responsive">
    <table class="table table-striped" id="table-speech">
        <thead>
            <tr>                
                <th>Número</th>
                <th>Tema</th>
            </tr>
        </thead>

        <tbody>
            {% for speech in object_list %}
            <tr>                
                <td> {{ speech.number }} </td>
                <td> {{ speech.theme }} </td>
            </tr>
            {% empty %}
            <tr>
                <td>Nenhum registro.</tD>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}

{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table-speech').DataTable({
            responsive: true,
            // "bSort": false,
            "aaSorting": [[0, "asc"]],
            "pageLength": 50,
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registos no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "A carregar dados...",
                "processing": "A processar...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            }
        });
    });
</script>
{% endblock %}

jwcm/public_speeches/templates/public_speeches/list_watchtower_reader.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}

{% block menu_items %}
    {% include 'public_speeches/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>{{title}}</h3>

<hr>

<div class="table responsive">
    <table class="table table-striped" id="table-watchtower-reader">
        <thead>
            <tr>                
                <th>Data</th>
                <th>Leitor</th>
                <th>Opções</th>
            </tr>
        </thead>

        <tbody>
            {% for meeting in object_list %}
            <tr>                
                <td> {{ meeting.date|date:"Y/m/d" }} </td>
                <td> {{ meeting.watchtower_reader.full_name }} </td>
                <td>
                    <a href="{{meeting.get_watchtower_reader_update_url}}" class="btn btn-warning" title="Editar">
                        <i class="fas fa-pencil"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td>Nenhum registro.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}

{% block scripts %}
<script>
    $(document).ready(function () {
        $('#table-watchtower-reader').DataTable({
            responsive: true,
            // "bSort": false,
            "aaSorting": [[0, "desc"]],
            "pageLength": 50,
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registos no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "A carregar dados...",
                "processing": "A processar...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            }
        });
    });
</script>
{% endblock %}

jwcm/public_speeches/templates/public_speeches/menu_items.html
<li class="nav-item">
	<a class="nav-link active" aria-current="page" href="{% url 'public-assignment-list' %}">Arranjo de Oradores</a>
</li>
{% if request.user.is_superuser %}
<li class="nav-item">
	<a class="nav-link active" aria-current="page" href="{% url 'speech-list' %}">Discursos públicos</a>
</li>
{% endif %}
<li class="nav-item">
	<a class="nav-link active" aria-current="page" href="{% url 'person-guest-create' %}">Cadastro de Oradores Visitantes</a>
</li>
<li class="nav-item">
	<a class="nav-link active" aria-current="page" href="{% url 'watchtower-reader-list' %}">Leitor de A Sentinela</a>
</li>

jwcm/public_speeches/templates/public_speeches/person_guest.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block menu_items %}
    {% include 'public_speeches/menu_items.html' %}
{% endblock %}

{% block content%}
<h3>{{ title }}</h3>
<hr>

<form method="POST" id="form">
    {% csrf_token %}
	{{ form.full_name|as_crispy_field }}
    {{ form.telephone|as_crispy_field }}


    <label for="id_congregation" class="control-label">Congregação</label>
    {{ form.congregation }}
    <a href="{% url 'congregation-guest-create' %}" id="add_congregation" onclick="return showAddPopup(this);"><i class="fas fa-plus"></i></a>


    <br>

    <button type="submit" class="btn btn-success mt-3">
        <i class="fas fa-check"></i> {{ button }}
    </button>
</form>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
function showAddPopup(triggeringLink) {
    var name = triggeringLink.id.replace(/^add_/, '');
    href = triggeringLink.href;
    var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;
}
function closePopup(win, newID, newRepr, id) {
    $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
    win.close();
}

</script>
{% endblock %}